
version: 0.0
os: linux
files:
  # Que archivos se copiaran en la instancia
  - source: ./docker-compose.production.yml
    destination: /home/ubuntu/
  - source: scripts
    destination: /home/ubuntu/scripts

# Ciclo de vida del deployment 
hooks:
  ApplicationStop:  # Corregido el typo
    - location: ./scripts/application-stop.sh
      timeout: 300
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 300
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 300